block.c: import changes from A217MUBSCDXF2
Let's see what happens now

Error shown before:

../drivers/mmc/core/block.c:1818:22: error: redefinition of 'issue_type'

        enum mmc_issue_type issue_type;

                            ^

../drivers/mmc/core/block.c:1814:22: note: previous definition is here

        enum mmc_issue_type issue_type = mmc_issue_type(mq, req);

                            ^

1 error generated.

make[4]: *** [../scripts/Makefile.build:333: drivers/mmc/core/block.o] Error 1

make[3]: *** [../scripts/Makefile.build:637: drivers/mmc/core] Error 2

make[2]: *** [../scripts/Makefile.build:637: drivers/mmc] Error 2